version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.8.3-python3.10
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "hNdRjZxVtNOlWR24VmGZrcuw2e2SJdRIiQ-cWDNDqHk="
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      PYTHONPATH: /opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - C:\Users\jorge\Documents\Universidad\2025B\Inteligencia\Proyecto\Proyecto_BI\assignmentProyect01\src:/opt/airflow/src
      - ../queries:/opt/airflow/queries
      - ../dataset:/opt/airflow/dataset
      - ./logs:/opt/airflow/logs
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.8.3-python3.10
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "hNdRjZxVtNOlWR24VmGZrcuw2e2SJdRIiQ-cWDNDqHk="
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      PYTHONPATH: /opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ../src:/opt/airflow/src
      - ../queries:/opt/airflow/queries
      - ../dataset:/opt/airflow/dataset
      - ./logs:/opt/airflow/logs
      - ./requirements.txt:/requirements.txt
    command: scheduler

volumes:
  postgres-db-volume:
